NAUTILUS_SCRIPT_DIR=$HOME/.local/share/nautilus/scripts

mkdir -p $NAUTILUS_SCRIPT_DIR
# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS, NAUTILUS_SCRIPT_SELECTED_URIS,
# NAUTILUS_SCRIPT_CURRENT_URI, NAUTILUS_SCRIPT_WINDOW_GEOMETRY
echo "subl \$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" > $NAUTILUS_SCRIPT_DIR/sublime-this.sh
chmod +x $NAUTILUS_SCRIPT_DIR/sublime-this.sh
